create table phone_numbers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  updated_at timestamp with time zone,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  phone_number varchar
);